[package]
name = "msi"
version = "0.1.0"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>"]
description = "Read/write Windows Installer (MSI) files"
repository = "https://github.com/mdsteele/rust-msi"
keywords = ["msi", "windows", "installer"]
license = "MIT"

[dependencies]
cfb = "0.1"
