[package]
name = "msi"
version = "0.4.0"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>"]
description = "Read/write Windows Installer (MSI) files"
repository = "https://github.com/mdsteele/rust-msi"
keywords = ["msi", "windows", "installer", "package"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
byteorder = "1"
cfb = "0.6.1"
encoding = "0.2"
uuid = "0.8.1"

[dev-dependencies]
chrono = "0.4"
clap = "2.27"
pest = "2.1"
pest_derive = "2.1"
